### ISSUE TITLE
for in loop not handling extended arrays

### ISSUE THREAD

**Issue by tv-brendan-jefferis** [jdan/isomer#57]
Just a simple addition to handle iterating over arrays which have had prototype extended.

I suggest adding the following **hasOwnProperty** conditional.

File: **isomer.js**, (ln 262)

    Isomer.prototype.add = function (item, baseColor) {

    ...

    for (var i in paths) {
         if (paths.hasOwnProperty(i)) {
             this._addPath(paths[i], baseColor);
         }
     }

**Comment by jdan** [comment]
Good idea, and thanks for the suggestion. I'll get a fix out soon, but feel free to jump ahead of me and submit a PR.

**Comment by jdan** [comment]
Closed via #60
