### ISSUE TITLE
Transparency not working in 0.2.4

### ISSUE THREAD

**Issue by jonkeegan** [jdan/isomer#59]
Used to be able to pass a value for transparency when defining the color after r,g,b.

**Comment by jdan** [comment]
Hi @jonkeegan,

Do you have a particular example of this failing?

**Comment by jonkeegan** [comment]
Hmm...just tried this again with a fresh copy from the repo, and it worked. Sorry about that.

**Comment by jdan** [comment]
No worries - is the copy on npm broken?
