### ISSUE TITLE
Consider not using for-in iteration over normal arrays

### ISSUE THREAD

**Issue by whoeverest** [jdan/isomer#63]
Using `for (var i in arr)` seems to have a huge performance penalty. The benchmark: http://jsperf.com/for-in-vs-normal-array-iteration

And since loops are used in critical places of the framework (like adding objects to the scene) I think it will make a difference if we change them to normal loops.

I'd be happy to do it and send a pull request if you're okay with the idea.

**Comment by jdan** [comment]
Yeah go for it :) To be honest I never use `for in`, but I did in this library for some reason! Happy to review a PR.

**Comment by jdan** [comment]
Thanks for calling this out, btw.

**Comment by whoeverest** [comment]
Okay, I sent a PR. Honestly I thought for-in was used in more than one place, my bad. Fixed it nevertheless.
