### ISSUE TITLE
Adopt a style guide

### ISSUE THREAD

**Issue by whoeverest** [jdan/isomer#66]
I think it's a good idea for Isomer to adapt a specific code style guide. Since Gulp is already used as a build tool, we can maybe add a JS linter stream, along with a config file that defines what's allowed and what's not. I notice the code that people write in their forks of Isomer is not styled in the same way as master.

**Comment by jdan** [comment]
Not a bad idea :) Maybe integrate something like https://github.com/jscs-dev/node-jscs?

**Comment by whoeverest** [comment]
@jdan I submitted a RP. I added a new gulp task called 'lint' and added some rules to `.jscsrc` so we have a staring point. I also modified the files so that they conform to the rules. Here are all the rules that JSCS offers: http://jscs.info/rules.html

Please review, maybe I've added something unreasonable. :-)

**Comment by jdan** [comment]
@whoeverest did a first pass a little while ago.

And don't worry - this is more reasonable than anything I've ever written.
