### ISSUE TITLE
How to draw outline?

### ISSUE THREAD

**Issue by elfet** [jdan/isomer#75]
Here is an example: 
![Box](http://upload.wikimedia.org/wikipedia/commons/a/aa/GlowingCubeWithEdgeOutline.png)
Black line is outline.

**Comment by jdan** [comment]
Not possible :) If we switch to a WebGL backing we should be able to do this without much effort. As it stands we can't currently do this.

**Comment by RangerMauve** [comment]
Well, you could draw a perfectly black cube and then draw the colored one over top of it. Just make sure the black one is a little bit bigger.

**Comment by elfet** [comment]
@jdan Thanks! :)
@RangerMauve too difficult.
