### ISSUE TITLE
How to invert the _translatePoint function?

### ISSUE THREAD

**Issue by jweissman** [jdan/isomer#80]
In order to permit user interaction with the scene I'm trying to compute the inverse of the `_translatePoint()` utility function so that I can draw elements on the scene where the mouse is (at least with respect to the z=0 plane). 

I think I'm trying to determine what input `point.x` and `point.y` might have resulted in the output that `_translatePoint` gives, if that makes sense. 

I've actually come up with a solution by plugging the system of simultaneous equations into Wolfram Alpha:

    det = (tx[0][1] * tx[1][0]) - (tx[0][0] * tx[1][1])
    px = ((ox * tx[1][1]) + (oy * tx[1][0]) - (tx[1][0] * y) - (tx[1][1] * x)) / det
    py = ((-(ox * tx[0][1])) - (ox * tx[0][0]) + (tx[0][0] * y) + (tx[0][1] * x)) / det

Where `ox`, `oy` is the origin and `tx` is your transformation matrix. This actually works, and is only off by constant.

**Comment by jdan** [comment]
Hey @jweissman, I see you closed this issue - did you figure it out?

**Comment by jweissman** [comment]
Yeah, I think so -- the above equations do seem to actually invert the projection, with a small constant error (-4 or so in the y-axis of the projection.)
