### ISSUE TITLE
how to wireframe 2d figures?

### ISSUE THREAD

**Issue by deostroll** [jdan/isomer#81]
Say I draw a triangle using a Path and 3 Points the triangle ends up filled.

How to have the triangle with no fill, just the wireframe?

**Comment by whoeverest** [comment]
I don't think you can do that right now. Looking at the source, I see that when a shape is drawn, it's stroke and fill color are always the same:

https://github.com/jdan/isomer/blob/master/js/canvas.js#L27

**Comment by deostroll** [comment]
@whoeverest can you explain briefly the math behind how we draw this stuff - isometric drawings...

**Comment by deostroll** [comment]
I guess you have to do this manually. Add holes to the closed object. 

https://github.com/deostroll/cross-threejs/blob/35a9571cc5c3b8bf9762fca5a4be7129f6823bcd/src/main.js

Additionally, for non-closed figures, the procedure for extruding follows the same principle. You have to close the figure such that its thickness is very small, and then use the extrusion apis.
