### ISSUE TITLE
Bug with certain dimensions

### ISSUE THREAD

**Issue by twaddle** [jdan/isomer#82]
The `Pyramid` is upside down when using `400000` as the height. With `40000`, it works correctly.

```
var Point  = Isomer.Point;
var Shape  = Isomer.Shape;

var iso = new Isomer(document.getElementById("canvas"));
iso.add(Shape.Prism(Point.ORIGIN, 1, 1, 400000));
```

Also there is a bug when setting the third argument of a `Prism` to 400. With `40` and `4000`, it works fine.

In case it matters: I found this bug using the [playground](http://jdan.github.io/isomer/playground/).

**Comment by jdan** [comment]
Heya @twaddle,

I'm late to answer this one, sorry! I'm unable to repro in the playground, I entered the following code:

```js
var Point  = Isomer.Point;
var Shape  = Isomer.Shape;

var iso = new Isomer(document.getElementById("canvas"));
iso.scale = 0.5;
iso.add(Shape.Prism(Point.ORIGIN, 1, 1, 400));
```

but didn't see anything upside down. Do you have another example of code that doesn't work? Will reopen if so, thanks!

**Comment by twaddle** [comment]
Sorry, I miscommunicated. What I was trying to say is that for enormously large numbers, like 400000, the pyramid is upside down; I realize that one might not care to support such sizes. The code I posted above still produced the same result, although it doesn't happen if you include the line `iso.scale = 0.5;`.

**Comment by jdan** [comment]
Would you mind posting a screenshot? I'm unable to get the prism to go upside down.

Even though it's a big number it still sounds like a bug :)
