### ISSUE TITLE
Animating without leaving artifacts

### ISSUE THREAD

**Issue by aordono** [jdan/isomer#88]
Hi there,

I just started using isomer and I'm glad that this sort of geometry is finally brought to the canvas.

I'm not sure if it's only visible on my computer, but I noticed that when translations are added, the shapes leave a trail. I looked at other pens that used rotation and the same artifacts don't occur.

Does anyone else notice artifacts when animating shapes? I tried adjusting the frame rate but no luck. Feedback is welcome.

Here's a [pen](http://codepen.io/addyoh/pen/XjmYXq) I forked just to get started. Very crude, but you can see clearly how the blue pyramid on the bottom leaves a trail, while the pink pyramid rotates and leaves a circle at its base.

Thanks!

**Comment by KenoLeon** [comment]
You need to clear the canvas before rendering:

http://codepen.io/k3no/pen/rWGjLO?editors=1010

**Comment by aordono** [comment]
Thank you!

**Comment by KenoLeon** [comment]
Closing the issue then
