### ISSUE TITLE
Should I use isomer for a new project?

### ISSUE THREAD

**Issue by sergiocastrovale** [jdan/isomer#90]
I've noticed there haven't been many changes in the last months, and I'm worried the project has come to a halt.

My game will revolve heavily around an isometric map and the objects placed on it, and isomer seems like the lightweight engine I'm looking for, but I'm afraid to put my hands on a deprecated project. Should I?

**Comment by whoeverest** [comment]
I don't think @jdan is actively maintaining the project, save for accepting a pull request here and there. So probably no. :)

**Comment by sergiocastrovale** [comment]
Oh ok. I'm glad I asked! Thanks :)

**Comment by jdan** [comment]
Hi @sergiocastrovale!

I encourage you to try it out for an hour or two for prototype purposes, but Isomer is more of an art tool. Happy to answer any Qs!
