### ISSUE TITLE
Is there any way to move the camera?

### ISSUE THREAD

**Issue by williamjones0** [jdan/isomer#98]
I am trying to create a camera-like aspect with my Isomer 'game'. So far I've made x, y and z variables, checked for arrow keys down, changed the variables accordingly, and readded the scene at the new coordinates. But it's being overlayed on top of the old scene, which isn't what I want it to do. Is there any way to reset the canvas, so that I can achieve what I want to?

**Comment by dnkmdg** [comment]
If you inspect the code over at http://dev.icatserver.com/isomer/ you’ll see an example of how to clear the canvas and redraw the scene. Even if the camera is not changing view I still use the basic technique to redraw scenes between frames. 
Sorry for not having it in a repo, it’s a very old app.

**Comment by williamjones0** [comment]
Thanks, that works perfectly! I take it there's no actual camera in Isomer, though?
